### ISSUE TITLE
Not working on MacOS

### ISSUE THREAD

**Issue by smkjason** [OpenChemE/BrewLab#2]
I was having a lot of trouble downloading packages for this App. I believe it's the **kivy_*** packages. 

Could we maybe containerize this using Docker or something?

**Comment by jd4900** [comment]
Not sure if we can dockerize this because of the GUI. I'll do some research. I'm going to try building this on my Mac and see if I can get it to work and provide better instructions.

**Comment by jd4900** [comment]
Did you install kivy? I realize now that it is not in the README. 

Here is the link: https://kivy.org/doc/stable/installation/installation-osx.html

**Comment by smkjason** [comment]
I did but it kept complaining about it. Not really sure what is going on. I can look into it more.
